### ISSUE TITLE
Screen should stay on for a more reliable connection 

### ISSUE THREAD

**Issue by cameronaaron** [JJTech0130/ValidationRelay#8]

**Comment by cameronaaron** [comment]
@JJTech0130 Any thoughts on getting this merged?

**Comment by JJTech0130** [comment]
I can merge it, but I don't have Xcode setup to build and test right now to make a new release
Eventually was hoping to get the posix_spawn rewrite stuff working, but oh well. Can probably just remove the TestFlight extension version too, if the recommended thing is to just keep the screen on.

**Comment by JJTech0130** [comment]
Fixed in v1.8
